<?php
namespace FacturaScripts\Plugins\Contratos\Controller;

use FacturaScripts\Core\Lib\ExtendedController\EditController;
use FacturaScripts\Core\Model\Producto;
use FacturaScripts\Dinamic\Model\Cliente;
use FacturaScripts\Dinamic\Model\FacturaCliente;

class EditContratoServicio extends EditController
{

    public function getModelClassName(): string
    {
        return "ContratoServicio";
    }

    public function getPageData(): array
    {
        $data = parent::getPageData();
        $data["title"] = "ContratoServicio";
        $data["icon"] = "fas fa-search";
        return $data;
    }

    public function createViews()
    {
        parent::createViews(); // TODO: Change the autogenerated stub

        $this->createViewEditContratoServicio();
    }

    protected function loadData($viewName, $view)
    {
        parent::loadData($viewName, $view); // TODO: Change the autogenerated stub

        if ($this->request->query->get('action') === 'renovar'){
            $contrato = (Object) $view->model;

            if (strlen($contrato->codcliente) === 0 || strlen($contrato->idproducto) === 0){
                echo 'no cliente o no producto';
                return;
            }

            $factura = new FacturaCliente();

            $cliente = new Cliente();
            $cliente->loadFromCode($contrato->codcliente);
            $factura->setSubject($cliente);

            if (strlen($contrato->codpago) > 0)
                $factura->codpago = $contrato->codpago;


            if ($factura->save()){
                $linea = $factura->getNewLine();
                $producto = new Producto();
                $producto->loadFromCode($contrato->idproducto);

                $linea->idproducto = $producto->idproducto;
                $linea->idfactura = $factura->idfactura;
                $linea->descripcion = $producto->descripcion;
                $linea->referencia = $producto->referencia;
                $linea->cantidad = 1;
                $linea->pvpunitario = $contrato->importe_anual > 0 ? $contrato->importe_anual : $producto->precio;
                $linea->pvptotal = $contrato->importe_anual > 0 ? $contrato->importe_anual : $producto->precio;
//                $linea->iva = $producto->getTax();
                $linea->codimpuesto = $producto->getTax()->codimpuesto;

                if (!$linea->save())
                    return;

            }


            // Comprobar si hay importe


            // Si todo es correcto
            // --> Actualizar datos
            // --> Devolver a editContrato con el OK
        }


    }


    public function createViewEditContratoServicio(){
        $this->addButton('EditContratoServicio', [
            'action' => 'EditContratoServicio?code='.$this->request->query->get('code').'&action=renovar',
            'icon' => 'fas fa-plus',
            'label' => 'Renovar contrato',
            'type' => 'link'
        ]);
    }


}
